import { test, expect } from './fixtures/account'

test('checker languages match submissions and settings survive saving and reload', async ({ page }, testInfo) => {
  await page.route('**/api/runtimes', route => route.fulfill({ json: { items: [{ id: 'cpp17', label: 'C++17' }, { id: 'python314', label: 'Python' }] } }))
  await page.goto('/problems/new')
  await page.getByLabel('問題のタイトル').fill('構築問題')
  await page.getByRole('button', { name: '判定方法', exact: true }).click()
  await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption({ label: 'スペシャルジャッジ' })
  await expect(page.getByLabel('検証コードの言語').locator('option')).toHaveText(['C++17', 'Python'])
  await page.getByLabel('検証コードの言語').selectOption('python314')
  await page.getByLabel('検証コード', { exact: true }).fill('import sys\nassert int(sys.stdin.read()) == 7')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('.draft-status [role="status"]')).toHaveText('保存済み')
  const id = new URL(page.url()).searchParams.get('problem')!
  expect(id).toBeTruthy()
  await page.reload()
  await page.getByRole('button', { name: '判定方法', exact: true }).click()
  await expect(page.getByLabel('検証コードの言語')).toHaveValue('python314')
  await expect(page.getByLabel('検証コード', { exact: true })).toContainText('assert int(sys.stdin.read()) == 7')
  await expect(page.locator('#submission-language option')).toHaveText(['C++17', 'Python'])
  await page.screenshot({ path: testInfo.outputPath('checker-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('checker-mobile.png'), fullPage: true })
  await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption({ label: '通常判定（空白区切りで比較）' })
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('.draft-status [role="status"]')).toHaveText('保存済み')
  await page.reload()
  await page.getByRole('button', { name: '判定方法', exact: true }).click()
  await expect(page.getByLabel('検証コードの言語')).toHaveCount(0)
})
