import { expect, test } from './fixtures/account'

test('generators append numbered inputs, replace outputs, persist code and retain cases on failure', async ({ page }) => {
  const requests: Record<string, any>[] = []
  let verdict = 'AC'
  await page.route('**/api/my/submissions', async route => {
    const body = route.request().postDataJSON()
    requests.push(body)
    await route.fulfill({ json: { id: 'generation-job', status: 'QUEUED' } })
  })
  await page.route('**/api/my/submissions/generation-job', route => {
    const mode = requests.at(-1)?.generation.mode
    return route.fulfill({ json: { id: 'generation-job', status: 'DONE', result: { verdict, compileLog: verdict === 'CE' ? 'syntax error' : undefined,
      cases: mode === 'input' ? [{ output: '7 8\n' }, { output: '' }] : [{ output: '15\n' }, { output: '' }] } } })
  })
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await page.getByLabel('入力ジェネレータのコード', { exact: true }).fill('#include <iostream>\nint main(){int n;std::cin>>n;std::cout<<n;}')
  await page.getByLabel('開始ケース番号').fill('7')
  await page.getByLabel('生成件数').fill('2')
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByRole('button', { name: 'テストケースを追加' })).toBeDisabled()
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await expect(page.getByText('2件の入力を追加しました。')).toBeVisible()
  expect(requests[0]?.generation).toEqual({ mode: 'input', start: 7, count: 2 })
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('7 8\n')
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await page.getByLabel('種類').selectOption('output')
  await page.getByLabel('出力ジェネレータのコード', { exact: true }).fill('#include <iostream>\nint main(){int a,b;std::cin>>a>>b;std::cout<<a+b;}')
  await page.getByLabel('生成件数').fill('2')
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.getByText('2件の出力を更新しました。')).toBeVisible()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('15\n')
  expect(requests[1]?.generation).toEqual({ mode: 'output', start: 1, count: 2 })
  verdict = 'CE'
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.locator('.generator [role=alert]')).toContainText('syntax error')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('15\n')
  await page.getByRole('button', { name: 'generated_8.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('')
  await expect(page.getByRole('status').filter({ hasText: '保存済み' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await expect(page.getByLabel('入力ジェネレータのコード')).toContainText('std::cin>>n')
  await page.getByLabel('種類').selectOption('output')
  await expect(page.getByLabel('出力ジェネレータのコード')).toContainText('std::cout<<a+b')
  await page.route('**/api/my/submissions/generation-job', route => route.fulfill({ json: { status: 'DONE', result: { verdict: 'AC', cases: [{ outputFile: { id: '33333333-3333-4333-8333-333333333333', size: 16 << 20, sha256: 'a'.repeat(64) } }] } } }))
  await page.route('**/api/my/problems/*/test-files/*/complete', route => route.fulfill({ status: 400, json: {} }))
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.locator('.generator [role=alert]')).toBeVisible()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('15\n')
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('16 MiB files are applied by reference and the complete set stays within 512 MiB', async ({ page }) => {
  const { createHash } = await import('node:crypto')
  const content = `${'x'.repeat(1023)}\n`.repeat(16384)
  const size = Buffer.byteLength(content)
  const sha256 = createHash('sha256').update(content).digest('hex')
  let next = 1, completed = 0, downloads = 0
  let savedCases: { inputFile?: { size: number }, input: string }[] = []
  await page.route('**/api/my/problems/*', async route => {
    if (route.request().method() === 'PUT') savedCases = route.request().postDataJSON().draft.testCases
    await route.fallback()
  })
  await page.route('**/api/my/submissions', route => {
    const count = route.request().postDataJSON().generation.count
    const cases = Array.from({ length: count }, () => ({ outputFile: { id: `33333333-3333-4333-8333-${String(next++).padStart(12, '0')}`, size, sha256 } }))
    return route.fulfill({ json: { status: 'DONE', result: { verdict: 'AC', cases } } })
  })
  await page.route('**/api/my/problems/*/test-files/*/complete', route => {
    completed++
    const id = new URL(route.request().url()).pathname.split('/').at(-2)
    return route.fulfill({ json: { id, size, sha256 } })
  })
  await page.route('**/api/my/problems/*/test-files/*', route => route.fulfill({ json: { url: 'https://generated.example/file', size, sha256 } }))
  await page.route('https://generated.example/file', route => { downloads++; return route.fulfill({ contentType: 'text/plain', body: content }) })
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await page.getByLabel('入力ジェネレータのコード').fill('int main(){}')
  await page.getByLabel('生成件数').fill('32')
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.getByText('32件の入力を追加しました。')).toBeVisible()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText('16,777,216 / 16,777,216 bytes')
  await expect.poll(() => savedCases.length).toBe(32)
  expect(savedCases.every(item => item.inputFile?.size === size && item.input === '')).toBe(true)
  expect(completed).toBe(32)
  await expect.poll(() => downloads).toBe(1)
  await page.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await page.getByLabel('生成件数').fill('1')
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.locator('.generator [role=alert]')).toContainText('512 MiB')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.case-files li')).toHaveCount(32)
  expect(completed).toBe(32)
  expect(savedCases.length).toBe(32)
})

test('sidebar opens the generator workspace and links to its public guide', async ({ page }, testInfo) => {
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'ジェネレータ', exact: true })).not.toBeVisible()
  const menu = page.getByRole('navigation', { name: '問題作成メニュー' })
  await menu.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await expect(menu.getByRole('button', { name: 'ジェネレータ', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('heading', { name: 'ジェネレータ', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: /入出力ジェネレータの使い方/ })).toHaveAttribute('href', '/blog/generator-guide')
  await page.getByLabel('入力ジェネレータのコード').fill('int main(){}')
  await page.getByLabel('開始ケース番号').fill('7')
  await page.getByRole('button', { name: 'テストケースを確認' }).click()
  await expect(page.getByRole('heading', { name: /テストケース/ })).toBeVisible()
  await menu.getByRole('button', { name: 'ジェネレータ', exact: true }).click()
  await expect(page.getByLabel('開始ケース番号')).toHaveValue('7')
  await expect(page.getByLabel('入力ジェネレータのコード')).toContainText('int main(){}')
  for (const width of [375, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`generator-${width}.png`), fullPage: true })
  }
  await page.goto('/blog/generator-guide')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('入出力ジェネレータの使い方')
  await expect(page.locator('article pre')).toHaveCount(2)
  await expect(page.locator('article')).toContainText('512 MiB')
  await expect(page.locator('article')).toContainText('std::cin >> case_number')
  await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href', 'https://judge.example/blog/generator-guide')
  await page.goto('/blog')
  await expect(page.getByRole('link', { name: '入出力ジェネレータの使い方', exact: true })).toBeVisible()
})
