import { expect, test } from './fixtures/account'
test('failed deletion keeps the problem and the dialog open', async ({ page }) => {
  await page.goto('/problems/new?fresh=1')
  await page.locator('#problem-title').fill('残る下書き')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page).toHaveURL(/problem=/)
  await page.route('**/api/my/problems/*', route => route.request().method() === 'DELETE' ? route.abort() : route.fallback())
  await page.getByRole('button', { name: '問題管理', exact: true }).click()
  await page.getByRole('button', { name: '問題を削除', exact: true }).click()
  await page.getByRole('button', { name: '削除する', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('処理に失敗しました')
  await page.getByRole('button', { name: 'キャンセル', exact: true }).click()
  await expect(page.getByRole('heading', { name: '問題管理', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '問題文', exact: true }).click()
  await expect(page.locator('#problem-title')).toHaveValue('残る下書き')
})

for (const width of [320, 375, 414, 768, 1280]) {
  test(`management replaces the workspace at ${width}px and preserves editing`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 700 })
    await page.goto('/problems/new?fresh=1')
    await page.locator('#problem-title').fill('管理画面へ切り替え')
    await page.locator('#problem-source').fill('## 書きかけの本文\n\n$A+B$')
    await page.getByRole('button', { name: '問題管理', exact: true }).click()
    await expect(page.getByRole('heading', { name: '問題管理', exact: true })).toBeVisible()
    await expect(page.locator('#problem-source')).toBeHidden()
    await expect(page.locator('dialog[open]')).toHaveCount(0)
    await expect(page.getByRole('button', { name: '問題管理', exact: true })).toHaveAttribute('aria-current', 'page')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`management-${width}.png`) })
    await page.getByRole('button', { name: '問題文', exact: true }).click()
    await expect(page.locator('#problem-title')).toHaveValue('管理画面へ切り替え')
    await expect(page.locator('#problem-source')).toHaveText('## 書きかけの本文\n\n$A+B$', { useInnerText: true })
  })
}
