import { expect, test } from '@playwright/test'

test('split panes resize by pointer and keyboard without changing content', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto('/problems/new?fresh=1')
  const source = page.locator('#problem-source')
  await source.fill('## 幅を調整\n\n' + '長い文章です。'.repeat(100))
  const handle = page.getByRole('separator', { name: '編集欄とプレビューの幅を調整' })
  const before = (await page.locator('.source-pane').boundingBox())!.width
  const bounds = (await handle.boundingBox())!
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + 120)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width / 2 + 180, bounds.y + 120, { steps: 8 })
  await page.mouse.up()
  expect((await page.locator('.source-pane').boundingBox())!.width).toBeGreaterThan(before + 170)
  await expect(source).toHaveValue(/長い文章です。/)
  await handle.focus()
  await page.keyboard.press('Home')
  await expect(handle).toHaveAttribute('aria-valuenow', '30')
  await page.keyboard.press('ArrowRight')
  await expect(handle).toHaveAttribute('aria-valuenow', '32')
  await page.keyboard.press('End')
  await expect(handle).toHaveAttribute('aria-valuenow', '70')
  await handle.dblclick()
  await expect(handle).toHaveAttribute('aria-valuenow', '50')
  await page.getByRole('button', { name: '編集', exact: true }).click()
  await expect(handle).toBeHidden()
  await page.getByRole('button', { name: '分割', exact: true }).click()
  await expect(handle).toBeVisible()
  await page.setViewportSize({ width: 375, height: 800 })
  await expect(handle).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)).toBe(true)
})
