import { expect, test } from './fixtures/account'

test('line numbers track scrolling without rendering every line and names are unique', async ({ page }) => {
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  const input = page.getByLabel('入力', { exact: true })
  const content = Array.from({ length: 1000 }, (_, i) => String(i)).join('\n')
  await input.fill(content)
  const gutter = page.locator('.test-data-editor').first().locator('.line-gutter > div > div')
  expect(await gutter.count()).toBeLessThanOrEqual(Math.ceil(await input.evaluate(element => element.clientHeight) / 22) + 2)
  await input.evaluate(element => { element.scrollTop = 0; element.dispatchEvent(new Event('scroll')) })
  await expect(gutter.first()).toHaveText('1')
  await input.evaluate(element => { element.scrollTop = 2200; element.dispatchEvent(new Event('scroll')) })
  await expect(gutter.first()).toHaveText('100')
  await expect(input).toHaveValue(content)
  await page.getByLabel('テストケース名 1', { exact: true }).fill('sample')
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('テストケース名 2', { exact: true }).fill('sample')
  await expect(page.locator('.test-case-editor [role="alert"]')).toContainText('重複')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('未保存の変更があります')
  await page.getByLabel('テストケース名 2', { exact: true }).fill('large')
  await expect(page.getByRole('status')).toHaveText('保存済み')
})

for (const width of [320, 375, 414, 768, 1280]) {
  test(`one file selection switches both editors at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/problems/new')
    await page.getByRole('button', { name: 'テストケース', exact: true }).click()
    await page.getByRole('button', { name: 'テストケースを追加' }).click()
    await page.getByLabel('テストケース名 1', { exact: true }).fill('sample.txt')
    await page.getByLabel('入力', { exact: true }).fill('3 5')
    await page.getByLabel('出力', { exact: true }).fill('8')
    await page.getByRole('button', { name: 'テストケースを追加' }).click()
    await page.getByLabel('テストケース名 2', { exact: true }).fill('large.txt')
    await page.getByLabel('入力', { exact: true }).fill('100 200')
    await page.getByLabel('出力', { exact: true }).fill('300')
    const files = page.getByRole('navigation', { name: 'テストケース一覧' })
    await files.getByRole('button', { name: 'sample.txt', exact: true }).click()
    await expect(page.getByLabel('入力', { exact: true })).toHaveValue('3 5')
    await expect(page.getByLabel('出力', { exact: true })).toHaveValue('8')
    await expect(page.locator('.test-data-editor textarea')).toHaveCount(2)
    await files.getByRole('button', { name: 'large.txt', exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByLabel('入力', { exact: true })).toHaveValue('100 200')
    await expect(page.getByLabel('出力', { exact: true })).toHaveValue('300')
    await expect(files.getByRole('button', { name: 'large.txt', exact: true })).toHaveAttribute('aria-current', 'true')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`shared-files-${width}.png`), fullPage: true })
    page.on('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'ケース2を削除' }).click()
    await expect(page.getByLabel('入力', { exact: true })).toHaveValue('3 5')
    await expect(page.getByLabel('出力', { exact: true })).toHaveValue('8')
    await page.getByRole('button', { name: 'ケース1を削除' }).click()
    await expect(page.locator('.test-data-editor textarea')).toHaveCount(0)
    await expect(page.getByText('テストケースを追加して、入力と期待出力を登録してください。')).toBeVisible()
  })
}

test('case limit stays at 100 when TL changes', async ({ page }) => {
  await page.goto('/problems/new')
  await page.locator('#time-limit').fill('5000')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  const add = page.getByRole('button', { name: 'テストケースを追加' })
  for (let i = 0; i < 100; i++) await add.click()
  await expect(add).toBeDisabled()
  await expect(page.locator('#test-cases-title')).toContainText('100 / 100件')
  await expect(page.getByRole('status')).toHaveText('保存済み')
  await page.getByRole('button', { name: '問題文', exact: true }).click()
  await page.locator('#time-limit').fill('100')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(add).toBeDisabled()
  await expect(page.locator('#test-cases-title')).toContainText('100 / 100件')
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'ケース1を削除' }).click()
  await expect(add).toBeEnabled()
  await expect(page.locator('.case-files li')).toHaveCount(99)
  await expect(page.getByRole('status')).toHaveText('保存済み')
})
