import { expect, test } from './fixtures/account'

test('large test data renders only visible lines and names are unique', async ({ page }) => {
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  const input = page.getByLabel('入力', { exact: true })
  const content = Array.from({ length: 200_000 }, (_, i) => String(i)).join('\n')
  await page.locator('.test-data-editor input[type=file]').first().setInputFiles({ name: 'large.txt', mimeType: 'text/plain', buffer: Buffer.from(content) })
  const scroller = page.locator('.test-data-editor').first().locator('.cm-scroller')
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText(`${Buffer.byteLength(content).toLocaleString('en-US')} / 16,777,216 bytes`)
  await scroller.evaluate(element => { element.scrollTop = element.scrollHeight })
  await expect(input).toContainText('199999')
  expect(await page.locator('.test-data-editor').first().locator('.cm-line').count()).toBeLessThan(100)
  await input.fill('1\n2\n3')
  await expect(input.locator('.cm-line')).toHaveText(['1', '2', '3'])
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText('5 / 16,777,216 bytes')
  await page.getByLabel('テストケース名 1', { exact: true }).fill('sample')
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('テストケース名 2', { exact: true }).fill('sample')
  await expect(page.locator('.test-case-editor [role="alert"]')).toContainText('重複')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('未保存の変更があります')
  await page.getByLabel('テストケース名 2', { exact: true }).fill('large')
  await expect(page.getByRole('status')).toHaveText('保存済み')
})

for (const width of [320, 375, 414, 768, 1280]) {
  test(`one file selection switches both editors at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/problems/new')
    const title = page.locator('#problem-title')
    const difficulty = page.getByLabel('難易度（作問者設定）')
    const time = page.locator('#time-limit')
    await expect(difficulty).toBeEnabled()
    expect(await title.evaluate(element => !!(element.compareDocumentPosition(document.querySelector('#problem-difficulty')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
    expect(await difficulty.evaluate(element => !!(element.compareDocumentPosition(document.querySelector('#time-limit')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
    if (width === 1280) {
      expect((await title.boundingBox())!.x).toBeLessThan((await difficulty.boundingBox())!.x)
      expect((await difficulty.boundingBox())!.x).toBeLessThan((await time.boundingBox())!.x)
      expect((await difficulty.boundingBox())!.y).toBe((await time.locator('..').boundingBox())!.y)
    }
    await page.getByRole('button', { name: 'テストケース', exact: true }).click()
    await page.getByRole('button', { name: 'テストケースを追加' }).click()
    await page.getByLabel('テストケース名 1', { exact: true }).fill('sample.txt')
    await page.getByLabel('入力', { exact: true }).fill('3 5')
    await page.getByLabel('出力', { exact: true }).fill('8')
    await page.getByRole('button', { name: 'テストケースを追加' }).click()
    await page.getByLabel('テストケース名 2', { exact: true }).fill('large.txt')
    await page.getByLabel('入力', { exact: true }).fill('100 200')
    await page.getByLabel('出力', { exact: true }).fill('300')
    const files = page.getByRole('navigation', { name: 'テストケース一覧' })
    await files.getByRole('button', { name: 'sample.txt', exact: true }).click()
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('8')
    await expect(page.locator('.test-data-editor .cm-editor')).toHaveCount(2)
    await expect(page.getByRole('button', { name: 'ファイルを選択', exact: true })).toHaveCount(2)
    for (const input of await page.locator('.test-data-editor input[type=file]').all()) await expect(input).toBeHidden()
    const chooserPromise = page.waitForEvent('filechooser')
    await page.getByRole('button', { name: 'ファイルを選択', exact: true }).first().click()
    await (await chooserPromise).setFiles({ name: 'sample.txt', mimeType: 'text/plain', buffer: Buffer.from('3 5') })
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
    await files.getByRole('button', { name: 'large.txt', exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('100 200')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('300')
    await expect(files.getByRole('button', { name: 'large.txt', exact: true })).toHaveAttribute('aria-current', 'true')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`shared-files-${width}.png`), fullPage: true })
    page.on('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'ケース2を削除' }).click()
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('8')
    await page.getByRole('button', { name: 'ケース1を削除' }).click()
    await expect(page.locator('.test-data-editor .cm-editor')).toHaveCount(0)
    await expect(page.getByText('テストケースを追加して、入力と出力を登録してください。')).toBeVisible()
  })
}

test('case limit stays at 100 when TL changes', async ({ page }) => {
  await page.goto('/problems/new')
  await page.locator('#time-limit').fill('5000')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  const add = page.getByRole('button', { name: 'テストケースを追加' })
  for (let i = 0; i < 100; i++) await add.click()
  await expect(add).toBeDisabled()
  await expect(page.locator('#test-cases-title')).toContainText('100 / 100件')
  await expect(page.getByRole('status')).toHaveText('保存済み')
  await page.getByRole('button', { name: '問題文', exact: true }).click()
  await page.locator('#time-limit').fill('100')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(add).toBeDisabled()
  await expect(page.locator('#test-cases-title')).toContainText('100 / 100件')
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'ケース1を削除' }).click()
  await expect(add).toBeEnabled()
  await expect(page.locator('.case-files li')).toHaveCount(99)
  await expect(page.getByRole('status')).toHaveText('保存済み')
})

test('500,000 ten-digit integers are stored as an immutable large test file', async ({ page }) => {
  const fileId = '33333333-3333-4333-8333-333333333333'
  const content = `500000\n${Array(500_000).fill('1000000000').join(' ')}\n`
  const size = Buffer.byteLength(content)
  expect(size).toBe(5_500_007)
  let digest = ''
  let uploaded = 0
  await page.route(/\/api\/my\/problems\/[^/]+\/test-files$/, async route => {
    const body = route.request().postDataJSON()
    digest = body.sha256
    expect(body.size).toBe(size)
    await route.fulfill({ json: { id: fileId, url: 'https://s3.example.test/file', headers: { 'content-type': 'text/plain; charset=utf-8', 'x-amz-checksum-sha256': digest, 'x-amz-tagging': 'status=pending' } } })
  })
  await page.route(new RegExp(`/api/my/problems/[^/]+/test-files/${fileId}/complete$`), route => route.fulfill({ json: { id: fileId, size, sha256: digest } }))
  await page.route(new RegExp(`/api/my/problems/[^/]+/test-files/${fileId}$`), route => route.fulfill({ json: { url: 'https://s3.example.test/file', size, sha256: digest } }))
  await page.route('https://s3.example.test/file', async route => {
    const headers = { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'GET,PUT' }
    if (route.request().method() === 'PUT') {
      uploaded = route.request().postDataBuffer()?.length ?? 0
      await route.fulfill({ status: 200, headers })
    } else {
      await route.fulfill({ status: 200, headers, body: Buffer.from(content) })
    }
  })
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.locator('.test-data-editor input[type=file]').first().setInputFiles({ name: 'large.txt', mimeType: 'text/plain', buffer: Buffer.from(content) })
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  expect(uploaded).toBe(size)
  expect(size).toBeLessThan(16 * 1024 * 1024)
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText(`${size.toLocaleString('en-US')} / 16,777,216 bytes`)
})

test('file selection imports automatically and preserves the opposite side across reloads', async ({ page }, testInfo) => {
  async function select(label: string, files: Record<string, string | Buffer>, invalid = false) {
    const chooser = page.waitForEvent('filechooser')
    await page.getByRole('button', { name: `${label}を選択`, exact: true }).click()
    const picker = await chooser
    expect(picker.isMultiple()).toBe(true)
    await picker.setFiles(Object.entries(files).map(([name, content]) => ({ name, mimeType: 'text/plain', buffer: Buffer.isBuffer(content) ? content : Buffer.from(content) })))
    if (invalid) await expect(page.locator('.test-case-editor [role=alert]')).toBeVisible()
    else await expect(page.locator('.test-case-editor [role=status]')).toContainText('件更新しました。')
    await expect(page.getByRole('button', { name: `${label}を選択`, exact: true })).toBeEnabled()
  }
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByText('ファイルから一括追加', { exact: true }).click()
  await expect(page.getByRole('button', { name: '一括追加', exact: true })).toHaveCount(0)
  for (const input of await page.locator('.bulk-import input[type=file]').all()) {
    await expect(input).toBeHidden()
    await expect(input).not.toHaveAttribute('webkitdirectory')
    await expect(input).toHaveAttribute('accept', '.txt,text/plain')
  }
  await select('入力ファイル', { 'sum.txt': '3 5\n', 'empty.txt': '' })
  await expect(page.locator('.case-files li')).toHaveCount(2)
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
  await expect(page.getByLabel('出力', { exact: true })).toBeEmpty()
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByText('ファイルから一括追加', { exact: true }).click()
  await select('出力ファイル', { 'sum.txt': '8\n', 'output-first.txt': '42' })
  await expect(page.locator('.case-files li')).toHaveCount(3)
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('8')
  await select('入力ファイル', { 'output-first.txt': '21' })
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('21')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('42')
  // Updating output later must preserve both the imported and manually edited input.
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await page.getByLabel('入力', { exact: true }).fill('9')
  await select('出力ファイル', { 'sum.txt': '18' })
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('9')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
  const batches = [
    { files: { 'bad.txt': Buffer.from([0xff]) }, error: 'UTF-8' },
    { files: { 'bad.txt': '\0' }, error: '使用できない文字' },
    { files: { 'bad.csv': '' }, error: '.txt' },
    { files: { 'big.txt': Buffer.alloc(16 * 1024 * 1024 + 1) }, error: '16 MiB' },
    { files: Object.fromEntries(Array.from({ length: 99 }, (_, i) => [`case${i}.txt`, ''])), error: '100件' },
  ]
  for (const item of batches) {
    await select('入力ファイル', item.files, true)
    await expect(page.locator('.test-case-editor [role=alert]')).toContainText(item.error)
    await expect(page.locator('.case-files li')).toHaveCount(3)
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('9')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
  }
  await select('入力ファイル', { 'sum.txt': '10' })
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
  for (const width of [320, 375, 414, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole('button', { name: '入力ファイルを選択', exact: true })).toBeInViewport()
    await expect(page.getByRole('button', { name: '出力ファイルを選択', exact: true })).toBeInViewport()
    if (width === 375 || width === 1280) await page.screenshot({ path: testInfo.outputPath(`file-import-${width}.png`), fullPage: true })
  }
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.case-files li')).toHaveCount(3)
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('10')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
})

test('single-side import preserves stored opposite files and validates before mutation', async () => {
  const { importTestCaseFiles, mergeTestCases } = await import('../app/utils/import-test-cases')
  const file = (name: string, value = '') => new File([value], name)
  const storedFile = { id: '33333333-3333-4333-8333-333333333333', size: 16 << 20, sha256: 'a'.repeat(64) }
  const existing = Array.from({ length: 100 }, (_, i) => ({ name: `${i}.txt`, input: '', output: '', isSample: i === 0, ...(i < 16 ? { inputFile: storedFile, outputFile: storedFile } : {}) }))
  const snapshot = JSON.stringify(existing)
  const imported = await importTestCaseFiles([file('0.txt', '9')], 'input', existing)
  const merged = mergeTestCases(existing, imported, ['input'])
  expect(merged).toHaveLength(100)
  expect(merged[0]).toEqual({ name: '0.txt', isSample: true, input: '9', output: '', outputFile: storedFile })
  expect(merged.slice(1)).toEqual(existing.slice(1))
  const outputs = await importTestCaseFiles([file('0.txt', '18')], 'output', merged)
  expect(mergeTestCases(merged, outputs, ['output'])[0]).toEqual({ name: '0.txt', isSample: true, input: '9', output: '18' })
  await expect(importTestCaseFiles([file('0.txt', '\0')], 'input', existing)).rejects.toThrow('使用できない文字')
  await expect(importTestCaseFiles([file('0.txt'), file('0.txt')], 'input', existing)).rejects.toThrow('重複')
  // The retained output bytes count toward the combined limit.
  await expect(importTestCaseFiles([file('99.txt', '1')], 'input', existing)).rejects.toThrow('512 MiB')
  expect(JSON.stringify(existing)).toBe(snapshot)
})


test('sample checkbox controls the blue flag, survives rename and reload, and can be cleared', async ({ page }) => {
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('テストケース名 1', { exact: true }).fill('custom.txt')
  const checkbox = page.getByRole('checkbox', { name: 'サンプルケースにする' })
  await expect(checkbox).not.toBeChecked()
  await checkbox.check()
  const flag = page.getByRole('img', { name: 'サンプルケース', exact: true })
  await expect(flag).toBeVisible()
  await expect(flag).toHaveCSS('fill', 'rgb(36, 99, 212)')
  await page.getByLabel('テストケース名 1', { exact: true }).fill('renamed.txt')
  await expect(checkbox).toBeChecked()
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(checkbox).toBeChecked()
  await expect(flag).toBeVisible()
  await page.getByLabel('テストケース名 1', { exact: true }).fill('sample_unchecked.txt')
  await checkbox.uncheck()
  await expect(flag).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(checkbox).not.toBeChecked()
  await expect(flag).toHaveCount(0)
})
