import { expect, test } from './fixtures/account'
const problem = '/problems/11111111-1111-4111-8111-111111111111'

test('system tracking, persistent overrides, SSR and editor input survive theme changes', async ({ page }) => {
  const errors: string[] = []
  page.on('console', message => { if (/hydration/i.test(message.text())) errors.push(message.text()) })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto(problem)
  const select = page.getByRole('combobox', { name: '配色', exact: true })
  const body = page.locator('body')
  const editor = page.getByLabel('ソースコード', { exact: true })
  await expect(select).toHaveValue('system')
  await expect(body).toHaveCSS('background-color', 'rgb(21, 27, 35)')
  await editor.fill('int main() { return 42; }')
  await expect(page.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(21, 27, 35)')
  await select.selectOption('light')
  await expect(body).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(editor).toHaveText('int main() { return 42; }')
  await page.reload()
  await expect(select).toHaveValue('light')
  await expect(body).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await select.selectOption('dark')
  await page.emulateMedia({ colorScheme: 'light' })
  await page.reload()
  await expect(select).toHaveValue('dark')
  await expect(body).toHaveCSS('background-color', 'rgb(21, 27, 35)')
  expect(await (await page.request.get(problem)).text()).toContain('data-theme="dark"')
  await select.selectOption('system')
  await expect(body).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(body).toHaveCSS('background-color', 'rgb(21, 27, 35)')
  await expect(page.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(21, 27, 35)')
  await page.reload()
  await expect(select).toHaveValue('system')
  expect(errors).toEqual([])
})
for (const path of ['/', '/problems/new', '/blog/new']) {
  test(`mobile selector and navigation persistence: ${path}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 320, height: 740 })
    await page.goto(path)
    const select = page.getByRole('combobox', { name: '配色', exact: true })
    await select.selectOption('dark')
    const bounds = (await select.boundingBox())!
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(320)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
    await page.screenshot({ path: testInfo.outputPath('dark-mobile.png'), fullPage: true })
    await page.goto('/login')
    await expect(select).toHaveValue('dark')
    await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(21, 27, 35)')
  })
}
test('invalid preference falls back to system', async ({ page, context }) => {
  await context.addCookies([{ name: 'openoj-theme', value: 'invalid', url: 'http://127.0.0.1:13000' }])
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto('/')
  await expect(page.getByRole('combobox', { name: '配色', exact: true })).toHaveValue('system')
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(21, 27, 35)')
})
