import { expect, test, type Page } from '@playwright/test'
import { randomUUID } from 'node:crypto'

const origin = 'http://127.0.0.1:13002'
async function login(page: Page, name = 'alice') {
  await page.goto('/login')
  await page.getByLabel('メールアドレス').fill(`${name}@example.test`)
  await page.getByLabel('パスワード', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'ログイン', exact: true }).click()
  await expect(page).toHaveURL('/my')
}
async function seed(page: Page, title: string) {
  const id = randomUUID()
  const response = await page.request.put(`/api/my/problems/${id}`, { headers: { origin }, data: { version: 0, draft: { title, markdown: '## コンテスト本文\n整数を出力してください。', editorial: '## コンテスト解説\n答えは2です。', timeLimitMs: '1000', memoryLimitMb: '512', testCases: [{ input: '1', output: '2', isSample: true }] } } })
  expect(response.status()).toBe(200)
  return id
}
function localDate(value: number) {
  const date = new Date(value)
  return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
}

test('create, reorder and edit an unpublished contest; guests cannot inspect its problems', async ({ page, browser }, testInfo) => {
  await login(page)
  const first = await seed(page, 'コンテスト選択A')
  const second = await seed(page, 'コンテスト選択B')
  await page.goto('/my')
  const tabs = page.getByRole('navigation', { name: '作成したコンテンツ' })
  await expect(tabs.getByRole('button')).toHaveText(['問題', '記事', 'コンテスト', '提出履歴'])
  await tabs.getByRole('button', { name: 'コンテスト', exact: true }).click()
  await expect(page.getByRole('heading', { name: '作成したコンテスト', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '新規コンテスト', exact: true }).click()
  await expect(page.locator('.site-shell--editor')).toBeVisible()
  await page.getByLabel('コンテストタイトル', { exact: true }).fill('ブラウザ作成コンテスト')
  await page.getByLabel('説明（Markdown）').fill('## 開催案内\nどなたでも参加できます。')
  await expect(page.locator('.contest-preview')).toContainText('開催案内')
  // Saving from another section reveals the missing field instead of focusing a hidden input.
  await page.getByRole('button', { name: 'コンテストを作成', exact: true }).click()
  await expect(page.getByRole('button', { name: 'コンテスト設定', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByLabel('開始日時')).toBeFocused()
  await expect(page.getByLabel('誤答ペナルティ（分）')).toHaveValue('5')
  await page.getByLabel('開始日時').fill(localDate(Date.now() + 86400000))
  await page.getByLabel('終了日時').fill(localDate(Date.now() + 90000000))
  await page.getByRole('button', { name: '問題・配点', exact: true }).click()
  await page.getByRole('checkbox', { name: 'コンテスト選択A', exact: true }).check()
  await page.getByRole('checkbox', { name: 'コンテスト選択B', exact: true }).check()
  await page.locator(`#points-${first}`).fill('300')
  await page.getByRole('button', { name: 'コンテスト選択Bを上へ' }).click()
  await page.getByRole('button', { name: 'タイトル・説明', exact: true }).click()
  await expect(page.getByLabel('説明（Markdown）')).toHaveValue('## 開催案内\nどなたでも参加できます。')
  await page.screenshot({ path: testInfo.outputPath('contest-editor-desktop.png'), fullPage: true })
  for (const width of [320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    for (const name of ['タイトル・説明', '問題・配点', 'コンテスト設定']) {
      await page.getByRole('button', { name, exact: true }).click()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      if (width === 375) await page.screenshot({ path: testInfo.outputPath(`contest-${name}-mobile.png`), fullPage: true })
    }
    await page.getByRole('button', { name: 'サイドバーを展開', exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'サイドバーを折りたたむ', exact: true }).click()
  }
  await page.getByRole('button', { name: 'コンテストを作成', exact: true }).click()
  await expect(page).toHaveURL(/\/contests\/[a-f0-9-]{36}$/)
  const id = page.url().split('/').pop()!
  const saved = await (await page.request.get(`/api/my/contests/${id}`)).json()
  expect(saved.problems.map((p: { id: string }) => p.id)).toEqual([second, first])
  expect(saved.penaltyMinutes).toBe(5)
  await expect(page.getByRole('heading', { name: '開催案内', exact: true })).toBeVisible()
  for (const width of [1280, 320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`contest-detail-${width}.png`), fullPage: true })
  }
  const contestMenu = page.getByRole('navigation', { name: 'コンテストメニュー' })
  await contestMenu.getByRole('link', { name: '順位表', exact: true }).click()
  await expect(contestMenu.getByRole('link', { name: '順位表', exact: true })).toHaveAttribute('aria-current', 'location')
  await expect(page.getByRole('heading', { name: '公式順位表', exact: true })).toBeInViewport()
  await page.getByRole('link', { name: 'コンテストを編集', exact: true }).click()
  await page.getByRole('button', { name: 'コンテスト設定', exact: true }).click()
  await page.getByLabel('誤答ペナルティ（分）').fill('0')
  await page.getByRole('button', { name: '変更を保存' }).click()
  await expect(page.getByText('誤答ペナルティ 0 分 · 部分点なし')).toBeVisible()
  await page.goto('/my/contests')
  await expect(page).toHaveURL('/my?tab=contests')
  await expect(page.getByRole('button', { name: 'コンテスト', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('link', { name: 'ブラウザ作成コンテスト', exact: true })).toBeVisible()
  for (const width of [320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(tabs.getByRole('button', { name: 'コンテスト', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 375) await page.screenshot({ path: testInfo.outputPath('my-contests-mobile.png'), fullPage: true })
  }
  await page.goto('/contests')
  await expect(page.locator('main').getByRole('link', { name: /作成したコンテスト|新規コンテスト|コンテストを作成/ })).toHaveCount(0)
  const guest = await browser.newContext({ baseURL: origin })
  const reader = await guest.newPage()
  await reader.goto(`/contests/${id}`)
  await expect(reader.getByRole('heading', { name: 'ブラウザ作成コンテスト' })).toBeVisible()
  await expect(reader.getByRole('link', { name: 'コンテスト選択A', exact: true })).toHaveCount(0)
  expect((await guest.request.get(`/api/contests/${id}/problems/${first}`)).status()).toBe(404)
  expect((await guest.request.get(`/api/problems/${first}`)).status()).toBe(404)
  const csrf = await page.request.put(`/api/my/contests/${id}`, { headers: { origin: 'https://attacker.example' }, data: {} })
  expect(csrf.status()).toBe(403)
  await guest.close()
})

test('scheduled problems open for submission, then publish with editorial and source after the deadline', async ({ page, browser }, testInfo) => {
  test.setTimeout(60000)
  await login(page)
  const pid = await seed(page, '時間で公開する問題')
  const participant = await browser.newContext({ baseURL: origin })
  const bob = await participant.newPage()
  await login(bob, 'bob')
  const guest = await browser.newContext({ baseURL: origin })
  const id = randomUUID()
  const now = Date.now()
  const response = await page.request.put(`/api/my/contests/${id}`, { headers: { origin }, data: { title: '自動公開コンテスト', description: '', startsAt: new Date(now + 4000).toISOString(), endsAt: new Date(now + 20000).toISOString(), version: 0, problems: [{ id: pid, points: 100 }] } })
  expect(response.status()).toBe(200)
  expect((await guest.request.get(`/api/contests/${id}/problems/${pid}`)).status()).toBe(404)
  await expect.poll(async () => (await guest.request.get(`/api/contests/${id}/problems/${pid}`)).status(), { timeout: 10000 }).toBe(200)
  const live = await (await guest.request.get(`/api/contests/${id}/problems/${pid}`)).json()
  expect(live.editorial).toBeUndefined()
  await bob.goto(`/contests/${id}/problems/${pid}`)
  await expect(bob.getByRole('heading', { name: 'コンテスト本文', exact: true })).toBeVisible()
  await bob.getByLabel('ソースコード', { exact: true }).fill('int main(){}')
  await bob.getByRole('button', { name: '提出する', exact: true }).click()
  await expect(bob).toHaveURL(/\/my\/submissions\/[a-f0-9-]{36}$/)
  const sid = bob.url().split('/').pop()!
  await expect(bob.getByRole('link', { name: '時間で公開する問題', exact: true })).toHaveAttribute('href', `/contests/${id}/problems/${pid}`)
  expect((await guest.request.get(`/api/contests/${id}/submissions/${sid}`)).status()).toBe(404)
  const reader = await guest.newPage()
  await reader.goto(`/contests/${id}`)
  await expect(reader.getByRole('region', { name: '公式順位表', exact: true })).toContainText('bob')
  await reader.setViewportSize({ width: 375, height: 900 })
  expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await reader.screenshot({ path: testInfo.outputPath('contest-standings-mobile.png'), fullPage: true })
  await expect.poll(async () => (await guest.request.get(`/api/problems/${pid}`)).status(), { timeout: 25000 }).toBe(200)
  await reader.goto(`/contests/${id}/problems/${pid}?view=editorial`)
  await expect(reader.getByRole('heading', { name: 'コンテスト解説', exact: true })).toBeVisible()
  await expect(reader.getByRole('navigation', { name: '問題メニュー' }).getByRole('link', { name: '解説', exact: true })).toHaveAttribute('aria-current', 'page')
  for (const width of [320, 375, 414, 768]) {
    await reader.setViewportSize({ width, height: 900 })
    expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await reader.screenshot({ path: testInfo.outputPath(`contest-editorial-${width}.png`), fullPage: true })
  }
  await reader.goto(`/contests/${id}/submissions/${sid}`)
  await expect(reader.locator('pre')).toContainText('int main(){}')
  for (const width of [320, 375, 414, 768]) {
    await reader.setViewportSize({ width, height: 900 })
    expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await reader.screenshot({ path: testInfo.outputPath(`contest-submission-${width}.png`), fullPage: true })
  }
  await reader.goto(`/contests/${id}`)
  await expect(reader.getByText('コンテストは終了しました。以降の提出は練習扱いです。')).toBeVisible()
  await guest.close()
  await participant.close()
})
